name : 旅行日誌

permalink:  /:year/:month/:day/:title.html

# Markdown
markdown: rdiscount

timezone: Asia/Shanghai

encoding: utf-8

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"

    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"