name : 旅行日誌

permalink:  /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

timezone: Asia/Shanghai

encoding: utf-8

plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/page/:num/"

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"

    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
